2022-07-23 13:29:11,607 ERROR: Exception on /user/Whale [GET] [in /Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/mehultyagi/Check/microblog/app/routes.py", line 117, in user
    return render_template(
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 155, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/mehultyagi/Check/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/mehultyagi/Check/microblog/app/templates/user.html", line 42, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2022-07-23 13:30:33,838 INFO: Microblog startup [in /Users/mehultyagi/Check/microblog/app/__init__.py:52]
